import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class GetData{

  GetData({this.keyword});
  String keyword;
  Map body;

  // Future getData() async{

  //   try{
  //     String url = "https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro&explaintext&redirects=1&titles=$keyword";
  //     http.Response response = await http.get(url);

  //     String data = response.body;
  //     if(response.statusCode == 200){
  //       body = jsonDecode(data)['query']['pages'];
  //     }
  //     body.forEach((k, v){
  //       print(body[k]['extract']);
  //       return body[k]['extract'];
  //     });

  //   }
  //   catch(e){
  //     return "Unknown Error occured";
  //   }
  // }

  String getData(String keyword){
    if(keyword == "Wheat"){
      return " Wheat is a grass widely cultivated for its seed, a cereal grain which is a worldwide staple food. The many species of wheat together make up the genus Triticum; the most widely grown is common wheat (T. aestivum).\nThe archaeological record suggests that wheat was first cultivated in the regions of the Fertile Crescent around 9600 BCE. Botanically, the wheat kernel is a type of fruit called a caryopsis.\nWheat is grown on more land area than any other food crop (220.4 million hectares, 2014). World trade in wheat is greater than for all other crops combined. In 2017, world production of wheat was 730 million tonnes, with a forecast of 2019 production at 766 million tonnes, making it the second most-produced cereal after maize. Since 1960, world production of wheat and other grain crops has tripled and is expected to grow further through the middle of the 21st century. Global demand for wheat is increasing due to the unique viscoelastic and adhesive properties of gluten proteins, which facilitate the production of processed foods, whose consumption is increasing as a result of the worldwide industrialization process and the westernization of the diet.Wheat is an important source of carbohydrates. Globally, it is the leading source of vegetable protein in human food, having a protein content of about 13%, which is relatively high compared to other major cereals but relatively low in protein quality for supplying essential amino acids. When eaten as the whole grain, wheat is a source of multiple nutrients and dietary fiber.In a small part of the general population, gluten – the major part of wheat protein – can trigger coeliac disease, noncoeliac gluten sensitivity, gluten ataxia, and dermatitis herpetiformis.";
    }
    else if(keyword == "Mustard"){
      return " Description: The mustard plant is any one of several plant species in the genera Brassica and Sinapis in the family Brassicaceae (the mustard family). Mustard seed is used as a spice. Grinding and mixing the seeds with water, vinegar, or other liquids creates the yellow condiment known as prepared mustard. The seeds can also be pressed to make mustard oil, and the edible leaves can be eaten as mustard greens. \n\nAbout: \n\n1. Season: Rabi Crop (Sown in winter, harvested during spring) \n\n2. Temperature: 15-25°c is suitable for cultivation \n\n3. Annual Rainfall: More than 600-1000 mm \n\n4. Soil Type: Sandy to heavy clay soil is suitable for mustard crop but alluvial loam is best soil for mustard cultivation \n\n5. Drainage: Soil should be well drained because this crop cannot tolerate water-logging condition. \n\nCost of Mustard Seeds: 60-80 INR/Kg";
    }
    else if(keyword == "Banana"){
      return " Description: Banana is one of the most important commercial tropical fruits traded. Eve was said to have used banana leaves to cover her modesty in the Garden of Paradise as revealed from antiquity. Bananas are called the “Apple of Paradise”. It is also known as “Adam Fig”. Banana is a type of fruit from herbaceous plants of the genus Musa. Musa species grow in a wide range of environments and have varied human uses, ranging from the edible bananas and plantains of the tropics to cold-hardy fiber and ornamental plants. They have been a staple of the human diet since the dawn of recorded history. \n\nAbout: \n\n1. Season: Rabi Crop (Sown in winter, harvested during spring) \n\n2. Temperature: 10-40°C is suitable for cultivation \n\n3. Annual Rainfall: Mean rainfall 75 mm per month \n\n4. Soil Type: Rich loamy soil with good drainage, adequate fertility, moisture, and plenty of organic matter. Alluvial and volcanic soils are best for banana cultivation \n\n5. Drainage: Soil should be well drained. \n\nCost of Banana: 60-65 INR/Kg";
    }
    else if(keyword == "Rice"){
      return " Description: Rice is the most important food crop of India covering about one-fourth of the total cropped area and providing food to about half of the Indian population. Rice is one of the chief grains of India. Moreover, this country has the largest area under rice cultivation. As it is one of the principal food crops. It is, in fact, the dominant crop of the country. India is one of the leading producers of this crop. Rice is the basic food crop and being a tropical plant, it flourishes comfortably in a hot and humid climate. \n\nAbout: \n\n1. Season: Kharif Crop (Sown in monsoon beginning, harvested during the end of monsoon and beginning of winter) \n\n2. Temperature: 15-30°C is suitable for cultivation \n\n3. Annual Rainfall: Around 150-200 mm \n\n4. Soil Type: Silts, loams and gravels and can tolerate acidic as well as alkaline soils. However, deep fertile clayey or loamy soils which can be easily puddled into mud and develop cracks on drying are considered ideal for raising this crop. \n\n5. Drainage: Crop should be submerged. \n\nCost of Rice: 30-100 INR/Kg";
    }
    else if(keyword == "Chilly"){
      return " Description: Chilli is a spicy fruit used in cuisine preparations. It is mostly added as an ingredient in foods to make it spicy. As per the latest data, India tops the list in chilli production followed by China, Peru, Spain and Mexico. Indian chillies are known for their pungency and colour, especially the ones grown in Guntur district of Andhra Pradesh. Some of the chillies that are bigger in size are called bell peppers and are used as a vegetable. Chilli has various local names in India like lanka, mirchi etc. \n\nAbout: \n\n1. Season: Both Rabi and Kharif Crop (sowing of Chilli for the Kharif crop season takes place between July and August while for the Rabi season, Chilli is sown over October and November). \n\n2. Temperature: 20-25°C is suitable for cultivation \n\n3. Annual Rainfall: Around 600-650 mm \n\n4. Soil Type: Chillies need moisture for growth. It has been found that black soil which retains moisture is ideal in case they are grown as rainfed crops.Under irrigated conditions, the crop needs well-drained sandy loam with rich organic content. \n\n5. Drainage: Soil should be well drained. \n\nCost of Rice: 80-122 INR/Kg";
    }
    else if(keyword == "Cucumber"){
      return " Description: Cucumber plants are large in size, triangular in shape, have hairy leaves and yellow flowers. Cucumbers contain 96% water and are rich sources of Vitamin K and Molybdenum (Mb) used to cure kidney, and heart problems. Cucumbers are rich in beneficial antioxidants that may reduce the risk of such fatal conditions. Cucumbers are also known for potentially aiding weight loss since they are low in calories and have high water content. Cucumbers , apart from being nourishing veggies, can boost the health of your skin in a variety of ways. Cucumbers can help improve the overall texture, tone and appearance of your skin. There are so many cucumber varieties in India available so eat cucumbers and be healthy. \n\nAbout: \n\n1.Season: Zaid Crop (sown during winter in the month of november and harvested in summer around April or May). \n\n2. Temperature: 25-35°C is suitable for cultivation \n\n3. Annual Rainfall: Around 200-300 mm \n\n4. Soil Type: Sandy loam rich in organic matter \n\n5. Drainage: Soil should be well drained";
    }
    else if(keyword == "Cabbage"){
      return " Cabbage, comprising several cultivars of Brassica oleracea, is a leafy green, red (purple), or white (pale green) biennial plant grown as an annual vegetable crop for its dense-leaved heads. It is descended from the wild cabbage (B. oleracea var. oleracea), and belongs to the cole crops or brassicas, meaning it is closely related to broccoli and cauliflower. A cabbage generally weighs between 500 to 1,000 grams (1 to 2 lb). Smooth-leafed, firm-headed green cabbages are the most common, with smooth-leaved purple cabbages and crinkle-leafed savoy cabbages of both colours being rarer. \n\nAbout: \n\n1. Season:Cabbage is a cool-weather crop. Grow cabbage in spring so that it comes to harvest before the summer heat or start cabbage in mid to late summer so that it comes to harvest during the cool days of autumn, winter, or early spring. \n\n2. Temperature: The optimum soil temperature for growth is 60 to 65° F. Young plants exposed to temperatures below 45°F for a period of time may bolt or form loose heads. Cover plants if cold weather is expected.. \n\n3. Annual Rainfall: With regard to rainfall, the minimum annual rainfall for Cabbage is 500 mm while the average relative humidity is between 60 and 90%. \n\n4. Soil Type: Cultivation of cabbage is done mainly on sandy to heavy soils rich in organic matter. Early crops prefer light soil while late crops thrive better on heavier soils due to retention of moisture. \n\n5. Drainage: Soil rich in organic matter with good drainage is all that your cabbage plants need to thrive";
    }
    else if(keyword == "Cotton"){
      return " Cotton is a soft, fluffy staple fiber that grows in a boll, or protective case, around the seeds of the cotton plants of the genus Gossypium in the mallow family Malvaceae. The fiber is almost pure cellulose, and can contain minor percentages of waxes, fats, pectins, and water. Under natural conditions, the cotton bolls will increase the dispersal of the seeds. The plant is a shrub native to tropical and subtropical regions around the world, including the Americas, Africa, Egypt and India. The greatest diversity of wild cotton species is found in Mexico, followed by Australia and Africa.[1] Cotton was independently domesticated in the Old and New Worlds. \n\nAbout: \n\n1. Season: it is sown in April-May and is harvested in December-January that is before the winter frost can damage the crop.. \n\n2. Temperature: Cotton requires a minimum daily air temperature of 15 degrees C (60° F) for germination, 21-27 degrees C (70-80° F) for vegetative growth, and 27-32 degrees C (80-90° F) during the fruiting period. \n\n3. Annual Rainfall : Cotton grows in tropical and subtropical warm humid climates. Annual temperature requirement is 20°-28°C. Equitable temperature distribution and bright sunshine is desirable. Annual rainfall of 55-100 cm is ideal for cotton Cultivation. Rainfall during harvesting is harmful. \n\n4. Soil Type: Cotton is best grown in soils with an excellent water holding capacity. Aeration and good drainage are equally important as the crop cannot withstand excessive moisture and water logging. The major soil types suitable for cotton cultivation are alluvial, clayey and red sandy loam. \n\n5. Drainage: Cotton can grow in almost all well drained soils. However, suitable soils for achieving high yields are considered the deep well drained sandy loam soils, with enough clay, organic matter and a moderate concentration of nitrogen and phosphorus";
    }
    else if(keyword == "Onion"){
      return " The onion (Allium cepa L., from Latin cepa meaning onion) also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion which was classified as a separate species until 2010. Its close relatives include garlic, scallion, leek, and chive. This genus also contains several other species variously referred to as onions and cultivated for food, such as the Japanese bunching onion (Allium fistulosum), the tree onion (A. ×proliferum), and the Canada onion (Allium canadense). The name wild onion is applied to a number of Allium species, but A. cepa is exclusively known from cultivation. Its ancestral wild original form is not known, although escapes from cultivation have become established in some regions.The onion is most frequently a biennial or a perennial plant, but is usually treated as an annual and harvested in its first growing season. \n\nAbout : \n\n1. Season: The growing season for onions is in Fall or early Spring. That can be mid February or mid summer. Onions have a specific planting time unlike garlic. \n\n2. Temperature: Onions are adapted to a wide range of temperatures and they are frost tolerant. Leaf, root, and bulb development occurs in cool temperatures between 55° to 75°F. Optimal onion leaf growth occurs at 68° to 77°F (20° to 25°C). Once bulbing has begun onions easily tolerate temperatures higher than 75°F. \n\n3. Annual Rainfall: It requires about 70% relative humidity for good growth. It can grow well in places where the average annual rainfall is 650-750 mm with good distribution during the monsoon period. Areas with low (< 650 mm) or heavy rainfall (>750 mm) are not particularly suitable for rain-fed crops. \n\n4. Soil Type: Onions will grow in almost any soil from sandy loams to heavy clay. The soil should be firm. If your soil is heavy then you can introduce some organic compost or manure into the soil to help its moisture retaining properties. Onions prefer a slightly acidic soil - PH 5.5-6.5 is a good PH for growing onions \n\n5. Drainage: Cotton can grow in almost all well drained soils";
    }
    else if(keyword == "Corn"){
      return " Maize (/meɪz/ MAYZ; Zea mays subsp. mays, from Spanish: maíz after Taino: mahiz), also known as corn (North American and Australian English), is a cereal grain first domesticated by indigenous peoples in southern Mexico about 10,000 years ago. The leafy stalk of the plant produces pollen inflorescences (or tassels) and separate ovuliferous inflorescences called ears that when fertilised yield kernels or seeds, which are fruits. Maize has become a staple food in many parts of the world, with the total production of maize surpassing that of wheat or rice. \n\nAbout : \n\n1. Season: Maize crop is usually cultivated in India, from June to July, Sept to Oct and Jan to Feb seasons. For seed production, sowing during Nov to Dec is suitable since seed maturity will not coincide with the rainy season. \n\n2. Temperature: Maize is grown in temperatures between 18°C and 27°C during the day and around 14°C during the night. \n\n3. Annual Rainfall: Maize can successfully grow in areas receiving an annual rainfall of 60 cm, which should be well distributed throughout its growing stage. Crop needs more than 50% of its total water requirements in about 30 to 35 days after tasseling and inadequate soil moisture at grain filling stage results in a poor yield of shrivelled grains. \n\n4. Soil Type: For a better yield of maize, one should consider soils with good organic matter content having high water holding capacity. soils with a pH of 5.5 to 7.0 are preferred for maize farming. \n\n5. Drainage: Well-Drained soils";
    }
    else if(keyword == "Tomato"){
      return " The tomato is the edible berry of the plant Solanum lycopersicum,commonly known as the tomato plant. The species originated in western South America and Central America.The Mexican Nahuatl word tomatl gave rise to the Spanish word tomate, from which the English word tomato derived. Its domestication and use as a cultivated food may have originated with the indigenous peoples of Mexico. \n\nAbout : \n\n1. Season: Tomato plants generally need about three months of warm, summer-like weather to produce a great harvest. In the perfect conditions, you want to start planting your tomatoes a few weeks after the last frost date in your area. Although this may not be when you start preparing to plant, depending on your seeds \n\n2. Temperature: Germination is best around 21C. Keep seedlings and young plants around 18C (if possible!). Outside – above 15C and best not below 10C at night – \n\n3. Annual rainfall: The total water needed of tomatoes over the entire growing season is 786 mm of which 68 mm is supplied by rainfall. The remaining quantity (786 - 68 = 718 mm) has to be supplied by irrigation. \n\n4. Soil Type: Loam and sandy loam soils are best for tomato production, but these plants will grow in almost all soil types except heavy clay \n\n5. Drainage: Soil should be well drained";
    }
  }
}